### ISSUE TITLE
无法点歌

### ISSUE THREAD

**Issue by xnylym** [EveElseIf/MusicParty#11]
从网易云和bilibili点歌，提示
![image](https://user-images.githubusercontent.com/97097841/220222757-f1d91c48-a8a5-447e-8017-407e19beecb6.png)
从QQ音乐点歌提示成功，但是队列中没有歌曲

**Comment by EveElseIf** [comment]
音乐id是对应平台上某歌曲的标识，通常是数字或字母组成的字符串，不是你理解的歌名。
如果不清楚音乐id是什么，就只使用歌单点歌。
QQ音乐的问题可能是cookie有误或过期导致的。

**Comment by xnylym** [comment]
好的
