### ISSUE TITLE
用户绑定QQ账号时会出现页面错误

### ISSUE THREAD

**Issue by EaterL** [EveElseIf/MusicParty#12]
![QQ图片20230302175054](https://user-images.githubusercontent.com/106928057/222393576-19a4cca8-5f44-4de6-a951-6f63b2a3f73f.png)

**Comment by EaterL** [comment]
不好意思，是我自己配置错了

**Comment by TacitR** [comment]
> 不好意思，是我自己配置错了

请问错误在哪里呢 我也遇到了这个问题，如果绑定的不是cookie对应的qq号会报错
